# -*- coding: utf-8 -*-
"""K_DataPreprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vMhQo6wjbT4GReWTVT-n901paJD4YyMj
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

dataset = pd.read_csv('/content/drive/MyDrive/ML_TRAINING/Dataset/bank.csv')

dataset.isnull().any() #no nan values

dataset.isnull().sum() #no nan values

dataset.info()

type(dataset)

dataset.head(3)

dataset.drop("education",1, inplace=True)
dataset.drop("default",1, inplace=True)
dataset.drop("day",1, inplace=True)
dataset.drop("month",1, inplace=True)
dataset.drop("duration",1, inplace=True)

dataset

dataset.columns

u =dataset.iloc[:,0:5]
v= dataset.iloc[:,6:12]
x=pd.concat([u,v],axis=1, join="outer")  
y = dataset.iloc[:,5:6]

x

y

print(type(x),type(y))

x = x.values#converting df to arrays
y = y.values

x

y

x.shape

dataset["job"].unique()

dataset["marital"].unique()

dataset["housing"].unique()

dataset["contact"].unique()

dataset["poutcome"].unique()

x[0:5]

from sklearn.compose import ColumnTransformer # used to convert data to binary format
from sklearn.preprocessing import OneHotEncoder

#ct = ColumnTransformer([("instance name for onehotencoding",onehotencoderfunction,[column index numbers that are to be converted in to binary fotmat])],remainder = "passthrough")
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,4,5,9,10])],remainder = "passthrough")
x = ct.fit_transform(x)

x.shape

x[0:5]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

x_train.shape

y_train.shape

x_test.shape

y_test.shape

from sklearn.preprocessing import StandardScaler # [-3,3],[0,1]
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_train

